services:
  db:
    image: postgres:17-alpine
    container_name: tech_fest_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech_fest_app
    ports:
      - "8000:5000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
      # If you switch drivers, also switch the URL prefix accordingly:
      # DATABASE_URL: postgresql+psycopg://clinic:123@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
